development:
  adapter: postgresql
  encoding: utf8
  database: additional_development
  pool: 5
  username: johnvanarkelen
  password:
  host: localhost
  
test:
  adapter: postgresql
  encoding: utf8
  database: additional_test
  pool: 5
  username: johnvanarkelen
  password: 